create database if not exists vendas_sucos;

USE VENDAS_SUCOS;

create table produtos
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
primary key (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO BIT(1) NULL,
primary key (MATRICULA));

CREATE TABLE CLIENTES (
  CPF varchar(11) NOT NULL,
  NOME varchar(100) DEFAULT NULL,
  ENDERECO varchar(150) DEFAULT NULL,
  BAIRRO varchar(50) DEFAULT NULL,
  CIDADE varchar(50) DEFAULT NULL,
  ESTADO varchar(45) DEFAULT NULL,
  CEP varchar(8) DEFAULT NULL,
  DATA_NASCIMENTO date DEFAULT NULL,
  IDADE int(11) DEFAULT NULL,
  SEXO varchar(1) DEFAULT NULL,
  LIMITE_CREDITO float DEFAULT NULL,
  VOLUME_COMPRA float DEFAULT NULL,
  PRIMEIRA_COMPRA bit(1) DEFAULT NULL,
  PRIMARY KEY (CPF)
);

CREATE TABLE NOTAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE DEFAULT NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT DEFAULT NULL,
primary KEY (NUMERO));

CREATE TABLE ITENS_NOTAS
(NUMERO VARCHAR(5),
CODIGO_PRODUTO VARCHAR(10),
QUANTIDADE INT,
PRECO FLOAT,
primary key (NUMERO));

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
primary key (NUMERO));


