USE VENDAS_SUCOS;

ALTER TABLE notas ADD constraint FK_CLIENTES
foreign key (CPF) 
references clientes (CPF);

ALTER TABLE notas ADD constraint FK_VENDEDORES
foreign key (MATRICULA) 
references vendedores (MATRICULA);

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO)
REFERENCES NOTAS (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO_PRODUTO)
REFERENCES PRODUTOS (CODIGO);

