select 
TBP.SABOR as PRODUTO,
year(NF.DATA_VENDA) as ANO,
round(sum(INF.QUANTIDADE * INF.PRECO), 2) as VOLUME_FINANCEIRO
from notas_fiscais NF
inner join itens_notas_fiscais INF on NF.NUMERO = INF.NUMERO
inner join tabela_de_produtos TBP on INF.CODIGO_DO_PRODUTO = TBP.CODIGO_DO_PRODUTO
where year(NF.DATA_VENDA) = 2016
group by TBP.SABOR;


select VENDA_SUCO.PRODUTO, VENDA_SUCO.ANO, VENDA_SUCO.VOLUME_FINANCEIRO, round(sum((VENDA_SUCO.VOLUME_FINANCEIRO/VENDA_TOTAL.VOLUME_TOTAL)*100),2) as PERCENTUAL from
(select
TBP.SABOR as PRODUTO,
year(NF.DATA_VENDA) as ANO,
round(sum(INF.QUANTIDADE * INF.PRECO), 2) as VOLUME_FINANCEIRO
from notas_fiscais NF
inner join itens_notas_fiscais INF on NF.NUMERO = INF.NUMERO
inner join tabela_de_produtos TBP on INF.CODIGO_DO_PRODUTO = TBP.CODIGO_DO_PRODUTO
where year(NF.DATA_VENDA) = 2016
group by TBP.SABOR) VENDA_SUCO
inner join 
(select
year(NF.DATA_VENDA) as ANO,
sum(INF.QUANTIDADE * INF.PRECO) as VOLUME_TOTAL
from notas_fiscais NF
inner join itens_notas_fiscais INF on NF.NUMERO = INF.NUMERO
where year(NF.DATA_VENDA) = 2016) VENDA_TOTAL
on VENDA_SUCO.ANO = VENDA_TOTAL.ANO
group by VENDA_SUCO.PRODUTO, VENDA_SUCO.ANO, VENDA_SUCO.VOLUME_FINANCEIRO
order by VENDA_SUCO.VOLUME_FINANCEIRO DESC;

-- TAMANHO
SELECT VENDA_TAMANHO.TAMANHO, VENDA_TAMANHO.ANO, VENDA_TAMANHO.QUANTIDADE,
ROUND((VENDA_TAMANHO.QUANTIDADE/VENDA_TOTAL.QUANTIDADE) * 100, 2) AS PARTICIPACAO FROM 
(SELECT TP.TAMANHO, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA)) AS VENDA_TAMANHO
INNER JOIN 
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_TAMANHO.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_TAMANHO.QUANTIDADE DESC