-- LTRIM - LEFT TRIMER - Corta espaços da esquerda, RTRIM da direita, CONCAT, TRIM - dos dois lados, UCASE Uppercase, Lcase Lowercase,
-- SUBSTRING - Extrai uma string de uma string
-- LENGTH - Tamanho da string
-- INSTR - String esta dentro de outra string

select concat(NOME, ' (',CPF ,')') as RESULTADO from tabela_de_clientes;
select concat(NOME, ' - ' , ENDERECO_1, ', ', CEP, ', ', BAIRRO, ', ', CIDADE, '-', ESTADO) as CLIENTE from tabela_de_clientes;

-- DATAS

select adddate("2020-04-17", interval 1 year) as DAQUI_1_ANO;

select concat(curdate(), " - " ,current_time());
select current_timestamp();
select datediff('2021/01/01', '2020/01/01');
select dayname('1994/04/17');

select NOME, concat(TIMESTAMPDIFF(year, DATA_DE_NASCIMENTO, curdate()), ' anos') as IDADE from tabela_de_clientes;

-- DATAS
ADDDATE()
ADDTIME()
CONVERT_TZ()
CURDATE()
CURRENT_DATE()
CURRENT_TIME()
CURRENT_ TIMESTAMP()
CURTIME()
DATE_ADD()
DATE_FORMAT()
DATE_SUB()
DATE()
DATEDIFF()
DAY()
DAYNAME()
DAY OF MONTH()
DAY OF WEEK()
DAY OF YEAR()
EXTRACT()
FROM_DAYS()
FROM_UNIXTIME()
GET_FORMAT()
HOUR()
LAST_DAY()
LOCALTIME()
LOCALTIMESTAMP()
MAKEDATE()
MAKETIME()
MICROSECOND()
MINUTE()
MONTH()
MONTHNAME()
NOW()
PERIOD_ADD()
PERIOD_DIFF()
QUARTER()
SEC_TO_TIME()
SECOND()
STR_TO_DATE()
SUBDATE()
SUBTIME()
SYSDATE()
TIME_FORMAT()
TIME_TO_SEC()
TIME()
TIMEDIFF()
TIMESTAMP()
TIMESTAMPADD()
TIMESTAMPDIFF()
TO_DAYS()
UNIX_TIMESTAMP()
UTC_DATE()
UTC_TIME()
UTC_TIMESTAMP()
WEEK()
WEEKDAY()
WEEK OF YEAR()
YEAR()
YEARWEEK()

-- STRINGS 
ASCII
BIN
BIT_LENGTH
CHAR_LENGTH
CHAR
CHARACTER_LENGTH
CONCAT_WS
CONCAT
ELT
EXPORT_SET
FIELD
FIND_IN_SET
FORMAT
HEX
INSERT
INSTR
LCASE
LEFT
LENGTH
LIKE
LOAD_FILE
LOCATE
LOWER
LPAD
LTRIM
MAKE_SET
MID
NOT LIKE
NOT REGEXP
OCTET_LENGTH
ORD
POSITION
QUOTE
REGEXP
REPEAT
REPLACE
REVERSE
RIGHT
RLIKE
NOT RLIKE
RPAD
RTRIM
SOUNDEX
SOUNDS_LIKE
SPACE
STRCMP
SUBSTR
SUBSTRING_INDEX
SUBSTRING
TRIM
UCASE
UNHEX
UPPER