select * from tabela_de_clientes where bairro
in (select distinct bairro from tabela_de_vendedores);

---
-- NO EXEMPLO ABAIXO TRANSFORMAMOS UM QUERY EM UMA TABELA E USAMOS ELA DEPOIS
-- EH POSSIVEL CRIAR CAMPOS QUE TENHAM CONTAS
---
select X.EMBALAGEM, X.PRECO_MAX from
(select EMBALAGEM, max(PRECO_DE_LISTA) as PRECO_MAX from tabela_de_produtos
group by EMBALAGEM) X where X.PRECO_MAX >=10;
--

SELECT CPF, COUNT(*) FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT * from
(SELECT CPF, COUNT(*) as NUMERO_VENDAS 
FROM notas_fiscais 
WHERE YEAR(DATA_VENDA) = 2016 
GROUP BY CPF) SECONDARY_TABLE 
where SECONDARY_TABLE.NUMERO_VENDAS > 2000;

---
-- CRIANDO UMA VIEW COM A CONSULTA ANTERIOR
---
USE `sucos_vendas`;
CREATE OR REPLACE VIEW `VW_MINHA_VIEW` AS
SELECT CPF, COUNT(*) AS NUMERO_VENDAS FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF;

select * from VW_MINHA_VIEW where NUMERO_VENDAS > 2000;