// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	application "arquitetura-hexagonal/application"

	mock "github.com/stretchr/testify/mock"
)

// ProductReader is an autogenerated mock type for the ProductReader type
type ProductReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ProductReader) Get(id string) (application.ProductInterface, error) {
	ret := _m.Called(id)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(string) application.ProductInterface); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductReader creates a new instance of ProductReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductReader(t mockConstructorTestingTNewProductReader) *ProductReader {
	mock := &ProductReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
