// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	application "arquitetura-hexagonal/application"

	mock "github.com/stretchr/testify/mock"
)

// ProductServiceInterface is an autogenerated mock type for the ProductServiceInterface type
type ProductServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, price
func (_m *ProductServiceInterface) Create(name string, price float64) (application.ProductInterface, error) {
	ret := _m.Called(name, price)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(string, float64) application.ProductInterface); ok {
		r0 = rf(name, price)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(name, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Disable provides a mock function with given fields: product
func (_m *ProductServiceInterface) Disable(product application.ProductInterface) (application.ProductInterface, error) {
	ret := _m.Called(product)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(application.ProductInterface) application.ProductInterface); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(application.ProductInterface) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Enable provides a mock function with given fields: product
func (_m *ProductServiceInterface) Enable(product application.ProductInterface) (application.ProductInterface, error) {
	ret := _m.Called(product)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(application.ProductInterface) application.ProductInterface); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(application.ProductInterface) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *ProductServiceInterface) Get(id string) (application.ProductInterface, error) {
	ret := _m.Called(id)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(string) application.ProductInterface); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductServiceInterface creates a new instance of ProductServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductServiceInterface(t mockConstructorTestingTNewProductServiceInterface) *ProductServiceInterface {
	mock := &ProductServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
