// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	application "arquitetura-hexagonal/application"

	mock "github.com/stretchr/testify/mock"
)

// ProductPersistenceInterface is an autogenerated mock type for the ProductPersistenceInterface type
type ProductPersistenceInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ProductPersistenceInterface) Get(id string) (application.ProductInterface, error) {
	ret := _m.Called(id)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(string) application.ProductInterface); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: product
func (_m *ProductPersistenceInterface) Save(product application.ProductInterface) (application.ProductInterface, error) {
	ret := _m.Called(product)

	var r0 application.ProductInterface
	if rf, ok := ret.Get(0).(func(application.ProductInterface) application.ProductInterface); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.ProductInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(application.ProductInterface) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductPersistenceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductPersistenceInterface creates a new instance of ProductPersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductPersistenceInterface(t mockConstructorTestingTNewProductPersistenceInterface) *ProductPersistenceInterface {
	mock := &ProductPersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
