FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY ./full-cycle/docker/nginx/nginx.conf /etc/nginx/conf.d

# docker run rodney-nginx > Hello World
# docker run rodney-nginx Rodney > Hello Rodney


# docker build -t rodney-nginx .
# docker run -p 8080:80